stages:
- stage: DevApply
  dependsOn: DevPlan  #depends on Terraform plan 
  variables:
  - group: dev-group-vars
  jobs:
  - job: TerraformApply
    steps:
    - script: 'terraform init -input=false'
      displayName: 'Init'  
    - script: 'terraform apply -auto-approve -var="ARM_CLIENT_ID=$(ARM_CLIENT_ID)" -var="ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)" -var="ARM_TENANT_ID=$(ARM_TENANT_ID)"  -var="ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)"'
      displayName: 'Apply'